name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
       node-version: '17'
       cache: npm
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
